spring:
  datasource:
    username: esenyuscsigi0dx7oiet
    url: jdbc:mysql://aws-sa-east-1.connect.psdb.cloud/pasareladb?sslMode=VERIFY_IDENTITY
    password: pscale_pw_54Tr1lHKm5kOWeVq1owFAW9NGsNVfH9xzBnj3rBjEhu
  jpa:
    defer-datasource-initialization: 'false'
    hibernate:
      ddl-auto: update

