spring:
  datasource:
    username: pasarella_user
    url: jdbc:mysql://localhost:3306/pasarelladb
    password: pasarella_user
  jpa:
    defer-datasource-initialization: 'false'
    hibernate:
      ddl-auto: update

